model: BERT

architecture:
  backbone: BERT
  decoder: Token-level classifier

training:
  optimizer: AdamW

  learning_rate: 5e-5

  batch_size: 32
  epochs: 60

  seeds:
    - 2021
    - 2022
    - 2023
    - 2024
    - 2025

loss:
  type: Cross-entropy loss

input:
  train_max_seq_length: 256
  eval_max_seq_length: 256

optimization:
  weight_decay: 0.01
  warmup_proportion: 0.05
